#spring.datasource.url=jdbc:postgresql://194.242.57.93:5434/student_db?options=-c%20timezone=UTC&sslmode=disable
#spring.datasource.username=team3
#spring.datasource.password=team377
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#spring.boot.admin.client.url=http://sb-admin:8080
#spring.boot.admin.client.instance.service-url=http://student-m-team3-app:8080
#management.endpoints.web.exposure.include=*,health,info,loggers,logfile
#logging.file.name=logs/team1.log

#spring.application.name=SpringBootEmail1
#spring.mail.host = smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=nikkpawar16@gmail.com
#spring.mail.password=fntg qlgh eadg cbdh
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


spring.application.name=StudentManagementfinal4

spring.datasource.url = jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

#// JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host = smtp.gmail.com
spring.mail.port=587
spring.mail.username=nikkpawar16@gmail.com
spring.mail.password=fntg qlgh eadg cbdh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
